#  ________  _________  ________     
# |\   __  \|\___   ___\\   ____\    
# \ \  \|\ /\|___ \  \_\ \  \___|    
#  \ \   __  \   \ \  \ \ \  \       
#   \ \  \|\  \   \ \  \ \ \  \____  
#    \ \_______\   \ \__\ \ \_______\
#     \|_______|    \|__|  \|_______|

# BlocksToCommands (V.5.0.0 BETA) 2020
# API: Minecraft 1.8

# By ILoveAMac

# These are the messages non-admin players will receive
# The fundsDeducted and notEnoughFunds message has variables.
# ${cost} -> Value that was deducted from the payer's account.
# ${currency} -> Server currency as set below.
messages:
  mayNotPerformCommand: '&cYou do not have permission to perform this command.'
  mayNotBreakBlock: '&cYou do not have permission to break this block.'
  mayNotUseBlock: '&cYou do not have permission to use this block.'
  notEnoughFunds: '&cYou do not have enough ${currency} to use this block.' # e.g You do not have enough dollars to use this block.
  fundsDeducted: '&a${cost} ${currency} were deducted from your account.' # e.g 10 dollars were deducted from your account

# Server currency
currency: 'dollars'

# Additional configuration
options:
  adminShiftRemove: true # When enabled players with the perm btc.admin ac hold shift and break a BTC block to delete it
  interactSounds: true # Play sounds when players interact with BTC blocks

# Plugin perms
# btc.admin -> Give only to admins on server
# btc.use -> Give to players you want to use BTC blocks
# custom perms can be assigned to blocks too. If a block has a custom perm, a player needs btc.use and the custom set perm in order to use the block